CS EQU P3.7
RD_A EQU P3.6
WR_A EQU P3.5
INTR EQU P3.4
ADC_DATA EQU P1
LED_DISPLAY EQU P2
ORG 0000H
SETB P0.1;//PUMP ON
LJMP START
ORG 0050H
START: MOV ADC_DATA,#0FFH ; make P1 as input to read ADC output
MOV LED_DISPLAY,#0FH ; display value on LED
SETB INTR ; input port line for end of conversion (EOC)
REPEAT: LCALL ADC_READ
MOV LED_DISPLAY,A ; display on LED connected at P2
LCALL WAIT
SJMP REPEAT
WAIT:
CLR A;
JNB P2.7,UP;
JB P2.7,DOWN;
SJMP WAIT
ADC_READ: CLR CS ;make CS=0
CLR WR_A ;make WR=0
LCALL DELAY
SETB WR_A ; WR=1
SETB CS ;CS=1 ; giving a pulse to start the ADC
HERE1: JB INTR, HERE1 ; EOC PIN POLLING / check for
CLR CS ;CS=0
CLR RD_A ; RD=0
MOV A,ADC_DATA ; read the ADC value to
SETB RD_A
SETB CS
RET
DOWN:SETB P3.2; //BUZZER ON
CLR P3.1;// PUMP OFF
LCALL DOWNCOUNT;
SJMP DOWN
DOWNCOUNT:MOV R5,#08H;
MOV R6,#08;
LCALL DC;
SJMP DOWNCOUNT
DC:MOV DPTR,#Value;
MOV A,R5;
MOVC A,@A+DPTR;
MOV P0,A;
LCALL DELAY
DJNZ R5,DC
WAITS:JB P2.7,WAITS;
SJMP WAIT
RET
UP:SETB P3.0;
LCALL DOWER;
SJMP UP
DOWER:MOV R5,#08H;
MOV R6,#08;
LCALL DCC;
SJMP DOWER
DCC:MOV DPTR,#Value;
MOV A,R5;
MOVC A,@A+DPTR;
MOV P0,A;
DEC A;
LCALL DELAY
DJNZ R5,DC
WAITSS:JNB P2.7,WAITSS;
SJMP WAIT
RET
Value:DB 3FH,06H,5BH,4FH,66H,6DH,7DH,07H,7FH,6FH;
DELAY:MOV R2,#0FFH;
RPT2:MOV R3,#0FFH;
RPT1:DJNZ R3,RPT1;
DJNZ R2,RPT2;
RET
MDELAY:MOV R0,#02;
LCALL DELAY
DJNZ R0,MDELAY
RET
END

